server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
    gateway:
      routes:
        # id 路由唯一表示
        - id: DisasterSimulation
          # url路由目的地，支持lb和http两种
          uri: lb://DisasterSimulation
          #predicates： 路由断言，判断请求是否符合要求，符合则转发到路由目的地
          predicates:
            - Path=/simulation/**
          #filters 路由过滤器

        - id: InformationQuery
          uri: lb://InformationQuery
          predicates:
            - Path=/information/**
        - id: Measure
          uri: lb://Measure
          predicates:
            - Path=/measure/**, /evalution/**
        - id: DisasterSimulation
          uri: lb://DisasterSimulation
          predicates:
            - Path=/simulation/**

      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true #解决options请求被拦截问题
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: #允许那些网站的跨域
              - "*"
            allowedMethods: # 允许跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" #允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 #这次跨域检测的有效期
