server:
  port: 8010
spring:
  application:
    name: CommentManage
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
      server-addr: localhost:8848
      file-extension: yaml
      shared-configs:
        - data-id: Pro_man
      group: DEFAULT_GROUP
    gateway:
      routes:
        # id 路由唯一表示
        - id: ProfessionManage
          # url路由目的地，支持lb和http两种
          uri: lb://ProfessionManage
          #predicates： 路由断言，判断请求是否符合要求，符合则转发到路由目的地
          predicates:
            - Path=/Profession/**
          #filters 路由过滤器
          globalcors: # 全局的跨域处理
            add-to-simple-url-handler-mapping: true #解决options请求被拦截问题
            cors-configurations:
              '[/**]':
                allowedOriginPatterns: #允许那些网站的跨域
                  - "*"
                allowedMethods: # 允许跨域ajax的请求方式
                  - "GET"
                  - "POST"
                  - "DELETE"
                  - "PUT"
                  - "OPTIONS"
                allowedHeaders: "*" #允许在请求中携带的头信息
                allowCredentials: true # 是否允许携带cookie
                maxAge: 360000 #这次跨域检测的有效期
  datasource:
    url: jdbc:oracle:thin:@//121.40.151.171:1521/helowin
    username: LX
    password: TJ12345
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  compression:
    request:
      enabled: true
      min-request-size: 2048
